version: '3'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command: start-dev
    environment:
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://localhost:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin 
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://localhost:8080
      - KC_HOSTNAME_ADMIN=http://localhost:8080
    depends_on: 
      - db
    network_mode: "host" 
  db: 
    image: mysql:8.0.42-debian
    network_mode: "host" 
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    security_opt:
      - seccomp=unconfined
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
